'''
== Tick Reference

This section gives, in alphabetical order, examples of how to use each function in the tick api library.

====
`+` - Add a duration to an instant:
[source.code,clojure]
----
(t/+ (t/now)
     (t/new-duration 10 :minutes))
----
====

====
`-` - Subtract a duration to an instant:
[source.code,clojure]
----
(t/- (t/now)
     (t/new-duration 10 :hours))
----
====

====
`<<` - Go back in time a duration:
[source.code,clojure]
----
(t/<< (t/now) (t/new-period 10 :weeks))
----
====

====
`>>` - Go forward in time a duration:
[source.code,clojure]
----
(t/>> (t/now) (t/new-duration 10 :hours))
----
====

====
`<` - Before?
[source.code,clojure]
----
(t/< (t/instant "2000-01-01T00:00") (t/instant "2018-01-01T00:00"))
----
====

====
`>` - After?
[source.code,clojure]
----
(t/> (t/instant "2000-01-01T00:00") (t/instant "2018-01-01T00:00"))
----
====

====
`\<=` - Before or same time?
[source.code,clojure]
----
(t/<= (t/instant "2000-01-01T00:00") (t/instant "2018-01-01T00:00"))
----
====

====
`>=` - After or same time?
[source.code,clojure]
----
(t/>= (t/instant "2000-01-01T00:00") (t/instant "2018-01-01T00:00"))
----
====

====
`ago` - Give the time a duration ago:
[source.code,clojure]
----
(t/ago (t/new-duration 1 :hours))
----
====

====
`am` - Create an interval spanning the morning of a given date:
[source.code,clojure]
----
(t/am (t/date "2018-01-01"))
----
====

====
`at` - Make date-time from a date (given date `at` "time"):
[source.code,clojure]
----
(-> (t/date "2000-01-01") (t/at "00:00"))
----
====

====
`atom` - Create an holder for the current time:
[source.code,clojure]
----
(def clk (t/atom))
(t/time @clk)
----
====

====
`beginning` - Give the beginning of an interval:
[source.code,clojure]
----
(t/beginning (t/today))
----
====

====
`between` - Give a value for the duration between two instances:
[source.code,clojure]
----
(t/between (t/instant "2000-01-01T00:00") (t/instant "2018-01-01T00:00"))
----
====

====
`bounds` - Give the beginning and end of an interval:
[source.code,clojure]
----
(t/bounds (t/yesterday))
----
====

====
`clock` - Create a system clock or fixed clock:
[source.code,clojure]
----
(t/clock)
----
[source.code,clojure]
----
(t/clock (t/instant "2018-01-01T00:00"))
----
====

====
`coincident?` - Are two intervals the same?
[source.code,clojure]
----
(t/coincident? (t/today) (t/today))
----
====

====
`complement` - Give the inverse of a list of intervals.
[source.code,clojure]
----
(t/complement [(t/instant "2010-01-01T00:00")
	       (t/instant "2010-02-01T00:00")
	       (t/instant "2010-03-01T00:00")])
----
====

====
`concur` - Get the common interval (if any) of two intervals.
[source.code,clojure]
----
(t/concur (t/today) (t/new-interval (t/yesterday) (t/tomorrow)))
----
====

====
`concurrencies` - A sequence of times when intervals overlap:
[source.code,clojure]
----
(t/concurrencies (t/pm (t/today)) (t/new-interval (t/today) (t/tomorrow)))
----
====

====
`conj` - Return new collection with the original collection including a new date:
[source.code,clojure]
----
(t/conj [(t/yesterday) (t/today)] (t/tomorrow))
----
====

====
`date` - Get the date:
[source.code,clojure]
----
(t/date)
----
[source.code,clojure]
----
(t/date) (t/tomorrow)
----
[source.code,clojure]
----
(t/date (t/instant "2018-01-01T00:00"))
----
[source.code,clojure]
----
(t/date "2018-01-01")
----
====

====
`date-time` - Get the date-time:
[source.code,clojure]
----
(t/date-time)
----
[source.code,clojure]
----
(t/date-time (t/tomorrow)) 
----
[source.code,clojure]
----
(t/date-time (t/instant "2018-01-01T00:00"))
----
[source.code,clojure]
----
(t/date "2018-01-01T00:00")
----
====

====
`day-of-month` - Get the numerical day of the month:
[source.code,clojure]
----
(t/day-of-month)
----
[source.code,clojure]
----
(t/day-of-month "2018-01-01")
----
[source.code,clojure]
----
(t/day-of-month (t/tomorrow))
----
[source.code,clojure]
----
(t/day-of-month (t/instant "2018-01-01T00:00"))
----
====

====
`day-of-week` - Get the day of the week
[source.code,clojure]
----
(t/day-of-week)
----
[source.code,clojure]
----
(t/day-of-week (t/yesterday))
----
[source.code,clojure]
----
(t/day-of-week (t/instant "2018-01-01T00:00"))
----
[source.code,clojure]
----
(t/day-of-week "2018-01-01")
----
====

====
`days` - Convert a duration into days
[source.code,clojure]
----
(t/days (t/new-duration 24 :hours))
----
====

====
`dec` - Give the previous year:
[source.code,clojure]
----
(t/dec (t/year))
----
====

====
`difference` - Return the first collection without the second collection elements.
[source.code,clojure]
----
(t/difference [(t/yesterday) (t/today) (t/tomorrow)] [(t/today)])
----
====

====
`divide` - Divide a duration by another duration:
[source.code,clojure]
----
(t/divide (t/new-duration 1 :days) (t/new-duration 1 :hours))
----
====

====
`divide-by` - Split an interval into even sections of time:
[source.code,clojure]
----
(t/divide-by 10 {:tick/beginning (t/instant "2018-01-01T00:00")
	         :tick/end (t/instant "2018-01-10T00:00")})
----
====

====
`duration` - Give the duration of an interval:
[source.code,clojure]
----
(t/duration {:tick/beginning (t/instant "2018-01-01T00:00")
	     :tick/end (t/instant "2018-01-10T00:00")})
----
====

====
`end` - Give the end instance of an interval:
[source.code,clojure]
----
(t/end {:tick/beginning (t/instant "2018-01-01T00:00")
	:tick/end (t/instant "2018-01-10T00:00")})
----
====

====
`epoch` - Give the https://en.wikipedia.org/wiki/Unix_time[epoch]:
[source.code,clojure]
----
(t/epoch)
----
====

====
`extend` - Extend an interval by a duration:
[source.code,clojure]
----
(t/extend {:tick/beginning (t/instant "2018-01-01T00:00")
           :tick/end (t/instant "2018-01-10T00:00")}
  (t/new-period 10 :weeks))
----
====

====
`fields` - Get the field for a given time value:
[source.code,clojure]
----
(t/fields (t/time))
----
====

====
`group-by` - Group a collection of intervals by a given function.
[source.code,clojure]
----
(t/group-by t/year
            (map #(apply t/new-interval %)
                 (t/divide-by (t/new-duration 1 :days)
                              (t/new-interval (t/new-date 2000 12 29)
                                              (t/new-date 2001 1 2)))))
----
====

====
`hence` - Return an instant 15 minutes from now:
[source.code,clojure]
----
(t/hence (t/new-duration 15 :minutes))
----
====

====
`hour` - Give the hour of the day:
[source.code,clojure]
----
(t/hour (t/now))
----
====

====
`hours` - Give a duration in hours:
[source.code,clojure]
----
(t/hours (t/new-duration 2 :days))
----
====

====
`in` - Give an instance in a time zone:
[source.code,clojure]
----
(t/in (t/instant "2018-01-01T10:00") "Australia/Darwin")
----
====

====
`inc` - Give the next year:
[source.code,clojure]
----
(t/inc (t/year))
----
====

====
`inst` - Convert to `java.util.Date`:
[source.code,clojure]
----
(t/inst)
----
[source.code,clojure]
----
(t/inst (t/instant "2018-01-01T00:00"))
----
====

====
`instant` - Convert to `java.time.Instant`:
[source.code,clojure]
----
(t/instant (t/inst))
----
[source.code,clojure]
----
(t/instant "2018-01-01T00:00:00.000+09:30[Australia/Darwin]")
----
====

====
`int` - Give the year as an integer:
[source.code,clojure]
----
(t/int (t/year))
----
====

====
`intersection` - Give the intersection of two sequences:
[source.code,clojure]
----
(t/intersection [(t/year)]
                [(t/date "2017-01-01")
                 (t/date "2018-01-01")
                 (t/date "2019-01-01")])
----
====

====
`intersects?` - Does an interval intersect with another?
[source.code,clojure]
----
(t/intersects? [(t/year)]
               (t/inc (t/year)))
----
====

====
`long` - return an instant as a long:
[source.code,clojure]
----
(t/long (t/instant))
----
====

====
`max` - Give the last chronological date from multiple unordered dates:
[source.code,clojure]
----
(t/max (t/today) (t/tomorrow) (t/yesterday) (t/new-date 2018 11 11))
----
====

====
`micros` - Give a duration in microseconds:
[source.code,clojure]
----
(t/micros (t/new-duration 5 :minutes))
----
====

====
`microsecond` - Give the microsecond of an instant:
[source.code,clojure]
----
(t/microsecond (t/now))
----
====

====
`midnight` - Time at midnight:
[source.code,clojure]
----
(t/midnight)
----
====

====
`midnight?` - Is it midnight?
[source.code,clojure]
----
(t/midnight? (t/date-time))
----
====

====
`millis` - Give a duration in milliseconds:
[source.code,clojure]
----
(t/millis (t/new-duration 5 :minutes))
----
====

====
`millisecond` - Give the millisecond of an instant.
[source.code,clojure]
----
(t/millisecond (t/now))
----
====

====
`min` - Give the first chronological date from an unordered list of dates:
[source.code,clojure]
----
(t/min (t/today) (t/tomorrow) (t/yesterday) (t/new-date 2018 11 11))
----
====

====
`minutes` - Give a duration in minutes:
[source.code,clojure]
----
(t/minutes (t/new-duration 5 :hours))
----
====

====
`minute` - Give the minute of an instant:
[source.code,clojure]
----
(t/minute (t/now))
----
====

====
`month` - Get the month:
[source.code,clojure]
----
(t/month)
----
[source.code,clojure]
----
(t/month "2018-11-11")
----
====

====
`months` - Get the number of months in a duration:
[source.code,clojure]
----
(t/months (t/new-period 10 :months))
----
====

====
`nanos` - Get the number of nanoseconds in a duration:
[source.code,clojure]
----
(t/nanos (t/new-duration 5 :minutes))
----
====

====
`nanosecond` - Get the nanosecond of the time:
[source.code,clojure]
----
(t/nanosecond (t/now))
----
====

====
`new-date` - Created a new `java.time.LocalDate`

[source.code,clojure]
----
(t/new-date 2000 01 01)
----
[source.code,clojure]
----
(t/new-date)
----
====

====
[[new-duration]]
`t/new-duration` - Create a new duration.
[source.code,clojure]
----
(t/new-duration 10 :minutes)
----
NOTE: `new-duration` units are from _nanos_ to _days_. For larger units of time, see <<new-period,`new-period`>>.
====

====
`new-interval` - Create a new interval: a map with a `:tick/beginning` and a `:tick/end`
[source.code,clojure]
----
(t/new-interval (t/instant "2018-01-01T00:00") (t/instant "2019-01-01T00:00"))
----
====

====
[[new-period]]
`new-period` - Create a new duration:
[source.code,clojure]
----
(t/new-period 10 :weeks)
----
NOTE: `new period` is in units greater than days. For smaller units,
see <<new-duration,`new-duration`>>.
====

====
`new-time` - Create a new `java.time.LocalTime`
[source.code,clojure]
----
(t/new-time)
----
[source.code,clojure]
----
(t/new-time 12 00)
----
====

====
`noon` - Give the time at noon.
[source.code,clojure]
----
(t/noon)
----
====

====
`normalize` - From a time ordered sequence of disjointed intervals, return a
sequence of interval groups:
[source.code,clojure]
----
(count (t/normalize [(t/new-interval (t/instant "2000-01-01T00:00")
	     		             (t/instant "2000-01-02T00:00"))
                     (t/new-interval (t/instant "2000-01-02T00:00")
	      		             (t/instant "2000-02-02T00:00"))
                     (t/new-interval (t/instant "2000-06-01T00:00")
	      		             (t/instant "2000-06-09T00:00"))]))
----
====

====
`now` - Give _now_ as an instant:
[source.code,clojure]
----
(t/now)
----
====

====
`offset-by` - Give a `java.time.OffsetDateTime` of a specified instant with a
specified offset:
[source.code,clojure]
----
(t/offset-by (t/now) 1)
----
====

====
`offset-date-time` - Convert a `java.time.Instant` to a `java.time.OffsetDateTime`

[source.code,clojure]
----
(t/offset-date-time (t/zoned-date-time "2000-01-01T00:00:00Z[Australia/Darwin]"))
----
[source.code,clojure]
----
(t/offset-date-time)
----
====

====
`on` - Give a LocalDateTime for a given time `on` a given date:
[source.code,clojure]
----
(t/on (t/new-time 11 00) (t/new-date 2000 01 01))
----
====

====
`ordered-disjoint-intervals?` - Are the given intervals time-ordered and disjointed?
[source.code,clojure]
----
(t/ordered-disjoint-intervals? [(t/new-interval (t/instant "2000-01-01T00:00")
			       			(t/instant "2000-01-02T00:00"))
				(t/new-interval (t/instant "2000-01-02T00:00")
						(t/instant "2000-02-02T00:00"))])
----
====

====
`parse` - Give the most applicable instance for the input string:
[source.code,clojure]
----
(t/parse "1pm")
----
====

====
`pm` - Give an interval covering the afternoon of a given date:
[source.code,clojure]
----
(t/pm (t/today))
----
====

====
`range` - Give a lazy sequence of times from start to finish.
[source.code,clojure]
----
(t/range (t/date-time "2000-01-01T12:00")
	 (t/date-time "2000-01-01T12:05")
	 (t/new-duration 1 :minutes))
----
====

====
`relation` - Show the relation of two intervals:
[source.code,clojure]
----
(t/relation {:tick/beginning (t/instant "2018-01-01T00:00")
	     :tick/end (t/instant "2019-01-01T00:00")}
            {:tick/beginning (t/instant "2018-06-01T00:00")
	     :tick/end (t/instant "2019-06-01T00:00")})
----
[source.code,clojure]
----
(t/relation (t/today) (t/yesterday))
----
NOTE: see <<relation-yesterday-tomorrow,above>> for more.
====

====
`reset!` - Reset an atom clock with one 5 mins slow.
[source.code,clojure]
----
(def clk (t/atom))
(def clk2 (t/atom (t/<< (t/clock) (t/new-duration 5 :minutes))))
(t/reset! clk clk2)
----
====

====
`reset-vals!` - Reset an atom clock with one 5 mins slow, and give the
value of before and after.
[source.code,clojure]
----
(def clk (t/atom))
(def clk2 (t/atom (t/<< (t/clock) (t/new-duration 5 :minutes))))
(t/reset-vals! clk clk2)
----

====

====
`scale` - Increase an interval by a given duration:
[source.code,clojure]
----
(t/scale {:tick/beginning (t/instant "2018-01-01T00:00")
	  :tick/end (t/instant "2019-01-01T00:00")}
         (t/new-duration 10 :minutes))
----
====

====
`seconds` - Give a duration in seconds:
[source.code,clojure]
----
(t/seconds (t/new-duration 5 :minutes))
----
====

====
`second` - Give the second of time:
[source.code,clojure]
----
(t/second (t/now))
----
====

====
`time` - Give the time of an instant:
[source.code,clojure]
----
(t/time (t/now))
----
====

====
`today` - Give todays date:
[source.code,clojure]
----
(t/today)
----
====

====
`tomorrow` - Give tomorrows date:
[source.code,clojure]
----
(t/tomorrow)
----
====

====
`truncate` - Lessen precision of an instant:
[source.code,clojure]
----
(t/truncate (t/instant) :days)
----
====

====
`union` - Join two time-ordered sequences together into one ordered sequence
[source.code,clojure]
----
(t/union [(t/today)] [(t/yesterday) (t/tomorrow)])
----
====

====
`unit-map` - A map of units of time that tick works with:
[source.code,clojure]
----
(keys t/unit-map)
----
[source.code,clojure]
----
(:minutes t/unit-map)
----
====

====
`unite` - Unite concurrent intervals ordered by beginning:
[source.code,clojure]
----
(t/unite [(t/new-interval (t/instant "2000-01-01T00:00")
	 		  (t/instant "2000-01-02T00:00"))
	  (t/new-interval (t/instant "2000-01-01T00:00")
	  		  (t/instant "2000-02-02T00:00"))])
----
====

====
`units` - Give the appropriate units for a duration:
[source.code,clojure]
----
(t/units (t/new-duration 1000000001 :nanos))
----
====

====
`with` - Return a date with an altered field:
[source.code,clojure]
----
(t/with (t/today) :day-of-month 1)
----
====

====
`with-clock` - Get the time from a clock:
[source.code,clojure]
----
(def clk (t/>> (t/clock) (t/new-duration 5 :minutes)))
(t/with-clock clk (t/time))
----

====
====
`year` - Give the year:
[source.code,clojure]
----
(t/year)
----
[source.code,clojure]
----
(t/year "2000-01-01")
----
====

====
`year-month` - Give the year and month:
[source.code,clojure]
----
(t/year-month)
----
[source.code,clojure]
----
(t/year-month "2000-01-01")
----
====

====
`years` - Give a duration in years.
[source.code,clojure]
----
(t/years (t/new-period 10 :years))
----
====

====
`yesterday` - Give yesterdays date:
[source.code,clojure]
----
(t/yesterday)
----
====

====
`zone` - Give the time zone:
[source.code,clojure]
----
(t/zone)
----
[source.code,clojure]
----
(t/zone (t/zoned-date-time "2000-01-01T00:00:00Z[Australia/Darwin]"))
----
====

====
`zone-offset` - Give the `java.time.ZoneOffset` with a specified offset:
[source.code,clojure]
----
(t/zone-offset 1 30 59)
----
====

====
`zoned-date-time` - Create a `java.time.ZonedDateTime`:
[source.code,clojure]
----
(t/zoned-date-time)
----
[source.code,clojure]
----
(t/zoned-date-time "2000-01-01T00:00:00Z[Australia/Darwin]")
----

====
