= tick

A Clojure(Script) library for dealing with time. Intended as a
replacement for clj-time.

Based on Java 8 time (on the JVM) and js-joda (on JavaScript
runtimes).

[source,clojure]
----
(require [tick.alpha.api :as t])

;; Get the current time
(t/now)
----

== Status

Alpha: Ready to use with the caveat that the API might still undergo
minor changes.

== Install

Get the latest from https://clojars.org/tick[Clojars] and 
add to your `project.clj`, `build.boot` or `deps.edn`. 

To use tick with Shadow-CLJS, there are some https://github.com/henryw374/tick-on-shadow-cljs-demo[extra steps]

== Development

=== with Clojure

REPL with nREPL server

----
clj -Adev
----

Port is written to `.nrepl-port`.

Run tests with:

----
make test
----

=== with ClojureScript

Various options:

----
make figwheel
----

Then navigate to http://localhost:9500/figwheel-extra-main/auto-testing


Or, From the Clojure REPL type `(node)` to get a node repl.


== Documentation

- https://juxt.github.io/tick[Generated API docs]

== Acknowledgements

Tick is based on the same original idea as
https://github.com/jarohen/chime[Chime]. The motivation is to be
able to view timelines of remaining times while the schedule is
running. Thanks to James Henderson for his work on Chime.

In particular, special credit to Eric Evans for discovering Allen's
interval algebra and pointing out its potential usefulness,
demonstrating a working implementation of Allen's ideas in
link:https://github.com/domainlanguage/time-count[his Clojure library].

Thanks also to my esteemed colleagues Patrik Kårlin for his redesign of
the interval constructor function, and Henry Widd for porting to cljc.

== References

* https://github.com/dm3/clojure.java-time
* https://clojuresync.com/emily-ashley/
* https://github.com/aphyr/tea-time
* https://github.com/sunng87/rigui

== Copyright & License

The MIT License (MIT)

Copyright © 2016-2018 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
