= tick

A Clojure library for dealing with time.

== Install

Add to your lein or boot dependencies:

```
[tick "0.3.5"]
```

== Development

REPL with nrepl server

----
clj -Adev
----

Port is written to `.nrepl-port`.

Run tests with:

----
clj -Atest -e deprecated
----

== Documentation

- https://juxt.github.io/tick[Generated API docs]

== Discussion

The 'flow of time' complicates our systems and we can simplify them if
we separate the concept of a timeline from the 'flow' of time we
perceive.

For more information, see the author's talk at ClojuTRE-2016 on https://www.youtube.com/watch?v=odPAkEO2uPQ[The
Universe As A Value] where he argues that time is a perception.

== Acknowledgements

Tick is based on the same original idea as
https://github.com/jarohen/chime[Chime]. The motivation is to be
able to view timelines of remaining times while the schedule is
running. Thanks to James Henderson for his work on Chime.

In particular, special credit to Eric Evans for discovering Allen's
interval algebra and pointing out its potential usefulness,
demonstrating a working implementation of Allen's ideas in
link:https://github.com/domainlanguage/time-count[his Clojure library].

Thanks also to my esteemed colleague Patrik Kårlin for his redesign of
the interval constructor function.

== References

* https://clojuresync.com/emily-ashley/
* https://github.com/aphyr/tea-time

== Copyright & License

The MIT License (MIT)

Copyright © 2016-2018 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
