= tick

A Clojure(Script) library for dealing with time. Intended as a
replacement for clj-time.

Based on Java 8 time (on the JVM) and js-joda (on JavaScript
runtimes). We are considering an implementation based on https://github.com/tc39/proposal-temporal[Temporal], via
https://github.com/henryw374/tempo[Tempo] when it is available.

[source,clojure]
----
(require '[tick.core :as t])

;; Get the current time
(t/now)
----

See https://www.youtube.com/watch?v=UFuL-ZDoB2U[Henry Widd's talk at Clojure/North 2019] for some background

== Docs

https://host-22a9c.web.app[Full Tick Documentation]

== Top tips 

=== Instants 

Instants are not 'calendar-aware' - they just contain millis/nanos field representing an offset from the Unix epoch. 

Tick provides sugar over this when accessing properties of an Instant though. For example
`(t/day-of-week (t/now))` is fine. To make that work, tick first converts the Instant into a ZonedDateTime 
and the zone of that will be the browser's or jvm's timezone. To be explicit about the zone in that case we would do:  

[source,clojure]
----
(-> (t/now)
    (t/in "UTC")
    t/day-of-week)
----

The other case where this might come up is when formatting Instants to string. Adding a zone to the formatter fixes the problems.

=== Singular vs Plural ?

As with java.time, any functions working with amounts of time (ie Durations or Periods), 
will have names which are in the plural. Functions that
work with dates and times are singular. Knowing that, e.g. `t/second` vs `t/seconds` makes sense.

== Status

* tick.core - stable
* tick.alpha.interval - Alpha: Ready to use with the caveat that the API might still undergo
minor changes.

== Install

Get the latest from https://clojars.org/tick[Clojars] and
add to your `project.clj`, `build.boot` or `deps.edn`.

Tick versions 0.4.24-alpha and up require minimum Clojurescript version of 1.10.741

For Clojurescript users of Tick, see https://github.com/juxt/tick/blob/master/docs/cljs.adoc[docs/cljs.adoc], for
some discussion around Clojurescript build size.

Here is a one-liner to drop into a node repl with tick:

----
clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "RELEASE" } tick/tick {:mvn/version "RELEASE"} }}' -m cljs.main  -re node  --repl
----

== Development

image:https://circleci.com/gh/juxt/tick/tree/master.svg?style=svg["CircleCI", link="https://circleci.com/gh/juxt/tick/tree/master"]

=== Develop The Documentation Site

Build the html
----
make
----

Build the CLJS and start a figwheel repl+server
----
make dev-docs-cljs
----

Navigate to localhost:9500 in your browser

=== Build a production version of the Documentation Site

----
make release-docs-cljs
----

=== Develop Tick

Jack in with cider or equivalent method in other IDEs, and start the cljs build with:

----
(figwheel-start!)
----


And when you get a REPL you can run all the JVM tests with

----
(test-clj)
----

Or outside of the REPL run:

----
make test-all
----

which will run clojure, clojurescript (node) and clojurescript (chrome) tests.
JVM tests are currently running with https://github.com/lambdaisland/kaocha[Kaocha] while JS tests are using figwheel-main and the cljs-test-runner.

As long as you have you have started your repl with these aliases "-A:dev:test-clj", you can also run backend clojure tests in the repl with something like

----
(require '[kaocha.repl :as kr])
(kr/run :clj)
----

=== npm dependencies

For running the ClojureScript tests you will need the following npm dependencies installed:

----
sudo npm install -g karma-cli
sudo npm install -g karma
sudo npm install -g karma-chrome-launcher
sudo npm install -g karma-cljs-test
----

Check `.circleci/config.yml` for the versions that are known to work.

==== Setting `CHROME_BIN`

If you get an error similar to the following:

----
No binary for ChromeHeadless browser on your platform.
----

Set the environment variable `CHROME_BIN` to wherever Chrome or Chromium is installed on your platform.


=== Release

create a git tag.

`make install VERSION=your-tag` (this installs in ~/.m2 - check that things look ok)

`make deploy VERSION=your-tag`  - you need to have set up clojars credentials as per https://github.com/applied-science/deps-library

`git push origin new-tag-name`

== Acknowledgements

In particular, special credit to Eric Evans for discovering Allen's
interval algebra and pointing out its potential usefulness,
demonstrating a working implementation of Allen's ideas in
link:https://github.com/domainlanguage/time-count[his Clojure library].

Thanks also to my esteemed colleagues Patrik Kårlin for his redesign of
the interval constructor function, and Henry Widd for porting to cljc.

== References

* https://github.com/dm3/clojure.java-time
* https://clojuresync.com/emily-ashley/
* https://github.com/aphyr/tea-time
* https://github.com/sunng87/rigui

== Copyright & License

The MIT License (MIT)

Copyright © 2016-2021 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
