= Times and dates

In _tick_, times and dates are values from Java™'s `java.time` package.

== Construction

=== Times

If you asked a stranger for the time, you'd hopefully get an answer,
something like "15 minutes to midnight". It would be uncommon for them
to tell you the date and timezone also, unless you asked for it.

The idea of the 'local' time, that you might read on a wall clock, is
still a useful concept. From a functional programming perspective, you
might think of this as 'partial evaluation' as applied to time.

[%header,cols="l,a,m"]
|===
|Example|Description|Return type
|(time)|The time now, as local time|java.time.LocalTime
|(time "4pm")|16:00, local time|java.time.LocalTime
|(midnight)|Midnight|java.time.LocalTime
|(noon)|Noon|java.time.LocalTime
|===

=== Dates

To get the current date, call `(today)`. This will return a `java.time.LocalDate`.

[%header,cols="l,a,m"]
|===
|Example|Description|Return type
|(today)|Today's date|java.time.LocalDate
|(date "2017-01-20")|February 20th, 2017|java.time.LocalDate
|===

=== Date-times

Date-times represent a particular time on a particular date.

While `(time "8pm")` gives a local-time on any date, you may want that time on a particular date, say Valentine's Day in 2018. You need to reify (a word meaning to 'make concrete') that time with a date to make a date-time. We can reify with `on` and `at`. For example:

----
(-> (time "8pm") (on "2018-02-14"))
----

And if starting with a date, we can use `at`:

----
(-> (date "2018-02-14") (at "8pm"))
----

In both cases, a `java.time.LocalDateTime` is returned.

[%header,cols="l,a,m"]
|===
|Example|Description|Return type
|(noon (today))|Noon today|java.time.LocalDateTime
|(-> (time "8pm") (on "2018-02-14"))|8pm on 2018-02-14|java.time.LocalDateTime
|(-> (date "2018-02-14") (at "8pm"))|8pm on 2018-02-14|java.time.LocalDateTime
|===

NOTE: TODO ZonedDateTime, OffsetDateTime


=== Instants

Instants are points in time.

To get the instant representing the current time, call `(now)`. This will return a `java.time.Instant` at the most precision possible on your platform (the nearest millisecond, microsecond or nanosecond).

[%header,cols="l,a,m"]
|===
|Example|Description|Return type
|(now)|The time now (millisecond granularity)|java.time.Instant
|(epoch)|Constant for the 1970-01-01T00:00:00Z epoch instant|java.time.Instant
|===


== Derivation

=== Reification


=== Adjustment

NOTE: TODO Adjusters

NOTE: Increment/decrement to create tomorrow,yesterday

[%header,cols="l,a,m"]
|===
|Example|Description|Return type
|(midnight (today))|Midnight, last night (since midnight is the start of the day)|java.time.LocalDateTime
|(tomorrow)|Tomorrow's date|java.time.LocalDate
|(yesterday)|Yesterday's date|java.time.LocalDate
|===


=== Truncation

You might not need millisecond (or nanosecond) accuracy, so you can truncate to the nearest second `(truncate (now) :seconds)` (or nearest minute with `(truncate (now) :minutes)`).


== Comparison

TODO
