= Introduction

Tick is a comprehensive Clojure library designed to make it easier to
write programs that involve time and date calculations:

* Functions to manipulating time, easily and succinctly
* Powerful functions for slicing and dicing time intervals
* Implementation of link:https://en.wikipedia.org/wiki/Allen%27s_interval_algebra[Allen's interval algebra]
* Support for iCalendar serialization
* Scheduling

== Cross Platform
 
 In many business domains, dates are as fundamental as numbers and strings. It's often useful to have date-heavy 
 business logic portable across platforms and whilst sometimes we can get away with just switching the clj(s)-time 
 import for the compilation target, the fact that cljs-time doesn't have complete fidelity with clj-time often leaks out.
 
== Comparison to other time libraries

=== Java 8 time

Java 8's `java.time` API is both influenced by, and an improvement on,
Joda Time.

Many Clojure applications use clj-time which is based on Joda Time, but tick uses
http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html[**java.time**].

CAUTION: Because _tick_ is built on `java.time`, it requires Java 8 or higher.

Unlike older JDK dates and calendars, instances in
`java.time` are immutable so can be considered values in Clojure. For this reason, there is no reason to wrap these values. Consequently, there is full interoperability between _tick_ and `java.time`. Where _tick_ does not provide a part of java.time's functionality, `java.time` can be called directly.

=== clj-time and Joda Time

NOTE: TBD

== cljs-time
  
  clj-time is a wrapper over the great joda-time, but cljs-time is a wrapper over goog.date which
  in turn is a wrapper over mutable js Date objects. 
  
  This works ok as a proxy for Instant, but is not a great foundation for  Local dates etc. 
  
  The author of cljs-time, Andrew McVeigh, has said he would ideally move cljs-time off goog.date but is unlikely to
  do so at this point. For one thing, there could be more than a few current users relying on the JS Date nature
  of the cljs-time objects.
  
  Taking a fresh look at the date/time landscape, we now have JSR-310 and implementations in both Java and Javascript
  and so it is possible to create tick, which combines the greatness of JSR-310 with an expressive, cross-platform 
  Clojure api.


=== clojure.java-time

NOTE: TBD

=== Quartz

See https://dzone.com/articles/why-you-shouldnt-use-quartz

== Status

Tick is currently in _alpha_ status.
