== Clojurescript

There are extra considerations when using tick with Clojurescript

=== Shadow-CLJS

TL;DR to use tick on shadow, follow https://github.com/henryw374/tick-on-shadow-cljs-demo[this demo]

Tick uses an npm lib, `js-joda` which is packaged in http://cljsjs.github.io/[cljsjs]. Shadow ignores the 
`:foreign-libs` directive in the `deps.cljs` dependency file of that lib, so requires a shim to create
the namespace that would normally come from the foreign-lib directive.

In future, tick could instead require consumers to rely on `:npm-deps` directive in deps.cljs.

=== Dropping to java.time

Tick depends on https://github.com/henryw374/cljc.java-time[cljc.java-time] which is the easiest way to access the full
java.time api underneath tick. 

=== Timezones 

If you want to work with timezones, something like this, for example:
                     
----
 (tick/zone "Europe/London") 
----

add the following require:

----
[tick.timezone]
----

=== Formatting

If you want to create custom formatters from patterns, such as "dd MMM yyyy", add this require:

----
[tick.locale-en-us]
----

==== Reducing Tick Build Size

The extra requires for timezones and locales are have been done that way to allow a smaller payload, when the extra 
libraries are not being used. 

Minified, gzipped js-joda (what gets pulled in if you use anything of tick) is around 43k. It could be possible to take advantage
of tree-shaking with JSJoda, see https://github.com/juxt/tick/issues/33[this ticket] for discussion.
  
Timezone is an extra 26k, and Locale (just en-US) is an extra 45k

Tick uses the https://js-joda.github.io/js-joda/[js-joda] library, which aims to replicate the http://www.threeten.org/threetenbp/[three-ten-backport]
project. JS-Joda is broken down into a core project (what tick depends on) and additional timezone
and locale projects. 

The js-joda timezone dependency contains the timezone database, containing mappings between zone
names, their offsets from UTC, and daylight savings(DST) data.

Locale data is needed for custom date formatters which need particular symbols, such as M for month. 
Due to the size and complexity of using the js-joda-locale, the authors of js-joda-locale have created
https://github.com/js-joda/js-joda-locale#use-prebuilt-locale-packages[prebuilt locale packages], for specific 
locales. en-US is one which is currently packaged for cljs and can be used as suggested above.
 
=== OffsetTime and OffsetDateTime

OffsetTime is currently missing from JS-Joda (see 
https://github.com/js-joda/js-joda/issues/240[JS-Joda issue 240]). For now, tick uses LocalTime
as the implementation which is not ideal. 

OffsetDateTime is also missing but ZonedDateTime has the same functionality so this shouldn't be a problem.
