= Times & dates

In this chapter we introduce times & dates and how we can manipulate
them.

== Introduction

If we asked a stranger for the time they'd likely respond with the just time of day, for example, "a quarter to eight". It would be uncommon for them to tell you the date and timezone also, unless you asked for it. This is the same time that we learn to read as children, on analog watches and wall-clocks.

So let's start with asking _tick_ for the time of day, with the `time` function. We demonstate this with our first example:

.Getting the time
====
To get the current time, call `(t/time)` with no arguments:

[source.code#time,clojure]
----
(t/time)
----
====

NOTE: If you have enabled JavaScript, you'll see a button labelled `Eval` on the right of the code snippet. Press this button to instruct your browser to evaluate the _tick_ code and display the result. You can clear the result by pressing the button labelled `Clr`. Many of the code examples in this documentation can be evaluated like this.

But so we can continue with our time-telling story, let's get a _specific_ time of "a quarter to eight":

.Getting a specific time
====
To get a specific time of day, call `(t/time)` with a string argument:

[source.code#specific-time,clojure]
----
(t/time "19:45")
----
====

If we wanted to know the name of the day today, we might ask "what's the day today". In _tick_, we'd use the `day` function.

.Getting the name of the day
====
We can get the name of the day today like this:

[source.code,clojure]
----
(t/day-of-week (t/today))
----

Or, even just:

[source.code,clojure]
----
(t/day-of-week)
----

Or, the day tomorrow:

[source.code,clojure]
----
(t/day-of-week (t/tomorrow))
----
====

The time "a-quarter-to-eight tomorrow" is useful, but if we wanted to record events we'd soon want to ask the date too. In _tick_, dates are specific calendar dates in the Gregorian calendar and include a day, month and year. We can ask the date with the `date` function:

.Getting today's date
====
To get today's date, we use the `date` function without arguments:

[source.code#date,clojure]
----
(t/date)
----

Alternatively we can call `today`:

[source.code#today,clojure]
----
(t/today)
----
====

NOTE: On the Java platform a _tick_ date corresponds to a `java.time.LocalDate` instance, while in a JavaScript environment it corresponds to js-joda's `LocalDate`.

Like with `time`, we can get particular dates by calling `date` with a
string argument:

.Getting a specific date
====
To get June 21st (or 21st June! footnote:[iso-8601,Dates are so often subject to regional conventions. Therefore in _tick_, we always parse and format dates according to <<ISO8601,ISO 8601>>.]) in 2018:

[source.code,clojure]
----
(t/date "2018-06-21")
----
====

Now we can ask for both time and date, we can combine them into a _date-time_.

We can use the function `date-time` with no arguments to get the current time at the current date:

.Getting the current date-time
====
To get the current date-time, call `t/date-time` with no arguments:

[source.code,clojure]
----
(t/date-time)
----
====

As with `time` and `date`, we can use a string argument with `date-time`, as shown in <<example-specific-datetime>>.

[[example-specific-datetime]]
.Getting a specific date-time
====
To get the time of the  link:https://en.wikipedia.org/wiki/Armistice_of_11_November_1918[Armistice of Compiègne], use <<ISO8601,ISO 8601>>:

[source.code,clojure]
----
(t/date-time "1918-11-11T11:00")
----
====

A *date-time* is the time at a specific location on a specific calendar date. Since noon is established as the point at which the Sun crosses the meridian, and since the Earth is spherical and rotating, noon is the same time for everyone. Consequently, the world is split into time-zones, each at an offset to Coordinated Universal Time (UTC).

If we wish to compare times in different places, we need to capture
the local offset, as shown in <<example-datetime-local-offset>>.

[[example-datetime-local-offset]]
.Getting a specific date-time with a local offset.
====
The Armistice of Compiègne was agreed at 11:00 am Paris time. On November 11th, 1918, Paris was one hour ahead of UTC. To capture this offset we can use `offset-date-time`:

[source.code,clojure]
----
(t/offset-date-time "1918-11-11T11:00:00+01:00")
----
====

There is a problem with using time offsets—they can change for a given time zone, especially since many time zones practice Daylight Savings Time (link:https://www.timeanddate.com/time/dst/[DST]). To capture the actual time zone, rather than the offset in effect on a given date, we can use `zoned-date-time`, as shown in <<example-datetime-time-zone>>.

.Why not local-date?
****
Java and js-joda name classes representing dates and date-times with a prefix of 'Local'. Why doesn't _tick_ maintain this convention? The reason is that date-times (and dates especially) are _always_ local, so the use of this prefix is superfluous. However, in Java, it is useful to distinguish between `java.time.LocalDate` and `java.util.Date`, or in JavaScript, between js-joda's `LocalDate` and JavaScript's built-in `Date`. In these contexts, the 'Local' prefix makes sense.

In, _tick_, instances of Java's `java.util.Date` and JavaScript's `Date` are termed **inst**s, so the term *date* is unambiguous (i.e. _always_ local).
****

[[example-datetime-time-zone]]
.Getting a specific date-time in a time zone.
====
The Armistice of Compiègne was agreed at 11:00 am Paris time.
In the summer, Paris time moves one hour forward for Daylight Savings Time (DST). Although Paris did use Daylight Savings Time in 1918, link:https://www.timeanddate.com/time/change/france/paris[the clocks had already moved back (at midnight on 8th October)]. To capture the time zone, along with its various rules for calculating offsets, we can use `zoned-date-time`:

[source.code,clojure]
----
(t/zoned-date-time
 "1918-11-11T11:00:00Z[Europe/Paris]")
----
====

Rather than using **offset-date-time**s and **zoned-date-time**s, you should use **instant**s when you want UTC-based date-times and don't care about time-zones and 'local' time.

Since a *zoned-date-time* (and *offset-date-time*) captures the offset from UTC, we can convert these into **instant**s, as show in <<example-instant>>.

NOTE: On the Java platform, an *instant* is a `java.time.Instant` and replaces the flawed `java.util.Date`. In a JavaScript environment, js-joda provides an identical class.

[[example-instant]]
.Converting an *offset-date-time* to an *instant*
====
To convert an *offset-date-time* to an *instant*, call `instant`:

For example:

[source.code,clojure]
----
(t/instant (t/offset-date-time "1918-11-11T11:00:00+01:00"))
----
====

If you want to get an instant representing the current time in UTC, call `instant` without arguments.

.Get the current instant in UTC
====
To get the current *instant*, do this:

[source.code,clojure]
----
(t/instant)
----

Alternatively, you can just call `now`:

[source.code,clojure]
----
(t/now)
----
====

If you do need a `java.util.Date` or JavaScript Date, for instance, for interoperating with an existing library, use the `inst` function.

.Converting an *instant* to an *inst*
====
To convert the current *instant* to an *inst*:

[source.code,clojure]
----
(t/inst (t/now))
----

In this case, the same could be achieved with the zero-argument form of `inst`:

[source.code,clojure]
----
(t/inst)
----
====

That's it for our introduction. Now we'll return to constructing times
and dates.

== Construction

Time values are constructed with `new-time`.

.Creating a time value
====
To create the time 11 o'clock am:

[source.code,clojure]
----
(t/new-time 11 0)
----

`new-time` also has other forms to increase precision, for example, with seconds…

[source.code,clojure]
----
(t/new-time 23 59 59)
----

…and with nanoseconds

[source.code,clojure]
----
(t/new-time 23 59 59 999999)
----
====

.What's the difference between `time` and `new-time`?
****
Until now we've been using `time` to create time values, for example, `(t/time "11:00")`, but now we have started to use the `new-time` function. What's going on?

Values are created using _constructor functions_ in _tick_. There are also _conversion functions_, which are named after the value they convert _to_. For example, the `time` function is a conversion function which converts are string to a time value.

In _tick_, the names of constructor functions are prefixed with `new-` to prevent naming clashes with conversion functions.

These conventions have been taken from a link:https://stuartsierra.com/2016/01/09/how-to-name-clojure-functions[blog article from Stuart Sierra] on how to name Clojure functions.


****

Similarly, dates are constructed with `new-date`, a function which has 3 forms. The first, and most common form, requires 3 arguments: the year, month and day (of the month).

.Creating a date value
====
JUXT was incorporated on March 22nd, 2013. We can create this date with `new-date` like this:

[source.code,clojure]
----
(t/new-date 2013 3 22)
----
====

Likewise, year-months are constsructed from the year and the month:

.Creating a year-month value
====
[source.code,clojure]
----
(t/new-year-month 2013 3)
----
====

== Reification

While `t/time` and `t/new-time` return a time, you may want to provide a date for that time later on. We can reify with `t/on` and `t/at`.

.reify
****
+[+**ree**-__uh__-fahy, **rey**-+]+ footnote:[From link:http://www.dictionary.com/browse/reify[reify at dictionary.com]]

verb (used with object), re·i·fied, re·i·fy·ing.

. to convert into or regard as a concrete thing: _to reify a concept_.
****

You can think of a *time* (or a *date*) as being a partially defined *date-time*.

.Reifying a **date-time** from dates and times
====
If we have a date of `1918-11-11`, we can construct a *date-time* by giving the time of 11am with `at`:

[source.code,clojure]
----
(-> (t/date "1918-11-11") (t/at "11:00"))
----

Alternatively, if we have the time we can add the date:

[source.code,clojure]
----
(-> (t/time "11:00") (t/on "1918-11-11"))
----
====

We can also use reification to provide the location, with `in`. This
allows us to take a local *date-time* and produce either a
*zoned-date-time* or an *offset-date-time*.

.Reifying a **zoned-date-time** from dates and times
====
To construct the *zoned-date-time* of the Armistice of Compiègne with `time`, `on` and `in`:

[source.code,clojure]
----
(-> (t/time "11:00") (t/on "1918-11-11") (t/in "Europe/Paris"))
----

Alternatively, we can use `t/offset-by` in place of `t/in`, to produce an *offset-date-time*.

[source.code,clojure]
----
(-> (t/time "11:00") (t/on "1918-11-11") (t/offset-by 2))
----
====

== Conversion

With ``instant``s, ``inst``s (`java.util.Date`, JavaScript's `Date`),
``zoned-date-time``s and ``offset-date-time``s, it's easy to get stuck
with the wrong type. Therefore, _tick_ provides functions to convert
between them.

To convert between any of these types, simply call the eponymous
function corresponding to the destination type with the source type as
an argument.

.Converting between types
====
To convert between an `instant` and a `zoned-date-time`:

[source.code,clojure]
----
(t/zoned-date-time (t/now))
----

To convert between a `zoned-date-time` and an `instant`:

[source.code,clojure]
----
(t/instant (t/zoned-date-time))
----

To convert between an `instant` and an `inst`:

[source.code,clojure]
----
(t/inst (t/now))
----
====

It's also possible to convert from strings to their destination types,
which will involve parsing the string in to its most appropriate type
prior to conversion.

In Java, types are converted according to the rules in <<table-conversion>>.

.Converting between Java 8 types
[#table-conversion%header,cols="h,d,d,d,d"]
|===
|Convert between|to instant|to offset-date-time|to zoned-date-time|to inst
|from instant|identity|`OffsetDateTime/ofInstant`|`ZonedDateTime/ofInstant`|`Date/from`
|from offset-date-time|`.toInstant`|identity|`.toZonedDateTime`|`.toInstant`, `Date/from`
|from zoned-date-time|`.toInstant`|`.toOffsetDateTime`|identity|`.toInstant`, `Date/from`
|from inst|`.toInstant`|`.toInstant`, `OffsetDateTime/ofInstant`|`.toInstant`, `ZonedDateTime/ofInstant`|identity
|from String|parse|`OffsetDateTime/parse`|`ZonedDateTime/parse`|parse, then `Date/from`
|===

== Extraction

Culturally, we understand time via calendars and it is often desirable
to extract certain fields from time values.

The `day-of-week` function extracts the day (of the week) from a time value, such as date, as shown in <<example-extract-day>>.

[[example-extract-day]]
.Extracting fields from a date
====

[source.code,clojure]
----
(t/day-of-week (t/date "2018-07-09"))
----

[source.code,clojure]
----
(t/month (t/date "2018-07-09"))
----

[source.code,clojure]
----
(t/year (t/date "2018-07-09"))
----
====

Days of the week, and months of the year, are available as constants listed in <<constants>>.

[[constants]]
[%header]
.Tick constants and their corresponding host types
|===
|Tick|Java|JavaScript
|tick.alpha.api/MONDAY|java.time.DayOfWeek.MONDAY|DayOfWeek.MONDAY
|tick.alpha.api/TUESDAY|java.time.DayOfWeek.TUESDAY|DayOfWeek.TUESDAY
|tick.alpha.api/WEDNESDAY|java.time.DayOfWeek.WEDNESDAY|DayOfWeek.WEDNESDAY
|tick.alpha.api/THURSDAY|java.time.DayOfWeek.THURSDAY|DayOfWeek.THURSDAY
|tick.alpha.api/FRIDAY|java.time.DayOfWeek.FRIDAY|DayOfWeek.FRIDAY
|tick.alpha.api/SATURDAY|java.time.DayOfWeek.SATURDAY|DayOfWeek.SATURDAY
|tick.alpha.api/SUNDAY|java.time.DayOfWeek.SUNDAY|DayOfWeek.SUNDAY
|tick.alpha.api/JANUARY|java.time.Month.JANUARY|Month.JANUARY
|tick.alpha.api/FEBRUARY|java.time.Month.FEBRUARY|Month.FEBRUARY
|tick.alpha.api/MARCH|java.time.Month.MARCH|Month.MARCH
|tick.alpha.api/APRIL|java.time.Month.APRIL|Month.APRIL
|tick.alpha.api/MAY|java.time.Month.MAY|Month.MAY
|tick.alpha.api/JUNE|java.time.Month.JUNE|Month.JUNE
|tick.alpha.api/JULY|java.time.Month.JULY|Month.JULY
|tick.alpha.api/AUGUST|java.time.Month.AUGUST|Month.AUGUST
|tick.alpha.api/SEPTEMBER|java.time.Month.SEPTEMBER|Month.SEPTEMBER
|tick.alpha.api/OCTOBER|java.time.Month.OCTOBER|Month.OCTOBER
|tick.alpha.api/NOVEMBER|java.time.Month.NOVEMBER|Month.NOVEMBER
|tick.alpha.api/DECEMBER|java.time.Month.DECEMBER|Month.DECEMBER
|===


We can use these constants to compare with `=` as shown in <<example-extract-day-with-compare>>.

[[example-extract-day-with-compare]]
.Comparing the day of the week from a date
====
Is the date 2018-07-09 is a Monday?

[source.code,clojure]
----
(= (t/day-of-week (t/date "2018-07-09")) t/MONDAY)
----

But is the month May?

[source.code,clojure]
----
(= (t/month (t/date "2018-07-09")) t/MAY)
----
====

The `ITimeLength` protocol provides functions to extract data from Durations & Periods.

Some examples

[%header,cols="l,a,l"]
|===
|Code|Description
|(t/seconds (t/new-duration 10 :seconds))|Seconds of a Duration
|(t/nanos (t/new-duration 10 :seconds))|Nanos of a Duration
|(t/days (t/new-period 100 :days))|Days of a Period
|===

== Comparison

TBD

== Modification

TBD

== Truncation

TBD
