= Intervals

In _tick_, an interval is a span of time defined by two points in time, the first being before the second.

Intervals are maps containing both a `tick/beginning` and a `tick/end` entry. This flexible design allows any Clojure map to be treated as an interval.

The start and end of an interval should have the same type.

Interval functions are currently alpha status and so reside in the `tick.alpha.interval` namespace, rather than the 
main `tick.core` namespace.

For example, bring in the interval functions like so:

----
(require '[tick.alpha.interval :as t.i])
----

== Construction

Obviously, the Clojure's literal syntax for maps can be used to create intervals.

====
Here we use a literal map syntax to construct an interval representing the last 5 minutes of 2018 (in UTC).

[source.code,clojure]
----
{:tick/beginning (t/instant "2018-12-31T23:55:00Z")
 :tick/end (t/instant "2019-01-01T00:00:00Z"})
----

====

Alternatively, we can use the `t.i/new-interval` function which takes the two boundaries of the interval as its arguments.

====
[source.code,clojure]
----
(t.i/new-interval
  (t/instant "2018-12-31T23:55:00Z")
  (t/instant "2019-01-01T00:00:00Z"))
----
====

== Derivation

Dates, months and years can also be considered to be themselves ranges, and can be converted to intervals with the `t.i/bounds` function. The start and end are both inclusive. This means for example that the `end` of one day `meets` the start of the next day.

====
To return today as an interval:

[source.code,clojure]
----
(t.i/bounds (t/today))
----
====

The arguments to `t.i/new-interval` do not have to be instants, they can be any time supported by _tick_.

====
To return a 2-day interval spanning midnight this morning to midnight [#eval-two-days-from-today]#two days from today#:
// Calculate the day today plus 2 days

[source.code,clojure]
----
(t.i/new-interval (t/today) (t/tomorrow))
----
====

== Comparison

Two intervals can be compared against each other with the `t.i/relation` function. link:https://en.wikipedia.org/wiki/Allen%27s_interval_algebra[Allen's interval algebra] tells us there are 13 possible relations between two intervals.

.Interval relations
====
Consider the time-span represented by the word 'yesterday' and compare it to the time-span represented by the word 'tomorrow'. Since yesterday is before tomorrow, with a gap between them, we say that yesterday _precedes_ tomorrow:

[source.code#relation-yesterday-tomorrow,clojure]
----
(t.i/relation (t/yesterday) (t/tomorrow))
----

If the two intervals touch each other, in the case of 'today' and 'tomorrow', then we say the first interval (today) _meets_ the second interval (tomorrow).

[source.code#relation-today-tomorrow,clojure]
----
(t.i/relation (t/today) (t/tomorrow))
----

To see other possible relations, use the slider in the diagram below to move the top interval along:

[.interval-relations]
----
abc
----
====

== Collections

It is often useful to group intervals into collections and have
functions operate on those collections.

For example, you may want to gather together:

* all the time intervals when you were working last week
* system outages over a given period
* public holidays and weekends this year

NOTE: Discuss ordered sequences of disjoint intervals.

== Demonstration
