= Setup

Get the latest from https://clojars.org/tick[Clojars] and 
add to your `project.clj`, `build.boot` or `deps.edn`. 

There are some docs/cljs.adoc[extra considerations when using tick from Clojurescript]. 

Here is a one-liner to drop into a node repl with tick:

---
clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "1.10.764" } tick {:mvn/version "0.4.24-alpha"} }}' -m cljs.main  -re node  --repl
---

== Serialization 

There are many use cases for de/serialization of dates, including simply being able to 
copy and paste within the REPL. Tick bundles https://clojars.org/time-literals[time-literals]
Clojure(Script) library, so having require'd tick, in your code or at the repl you can type

----
#time/period "P1D"
----

which is read as a java.time.Period (or js-joda Period in ClojureScript).

To avoid tick modifying the printer for java.time objects (if you already employ a custom set of literals for example),
set the following jvm property

```
 :jvm-opts ["-Dtick.time-literals.printing=false"]
```

To read and write edn data containing these literals in Clojure(Script) and for more information generally, see
the https://github.com/henryw374/time-literals[tagged literals Readme]

include::cljs.adoc[]